//! Closed shared-admin capacity equations for destructive group-offset owners.

use super::{
    ABORT_PARTITION_TRANSACTION_CAPACITY, ADD_RAFT_VOTER_CAPACITY,
    ADMIN_DESCRIBE_PRODUCERS_CAPACITY, ADMIN_DESCRIBE_TOPIC_PARTITIONS_CAPACITY,
    ADMIN_DESCRIBE_TRANSACTIONS_CAPACITY, ADMIN_FENCE_PRODUCERS_CAPACITY,
    ADMIN_LIST_OFFSETS_CAPACITY, ADMIN_LIST_TRANSACTIONS_CAPACITY, ALTER_CLIENT_QUOTAS_CAPACITY,
    ALTER_CONSUMER_GROUP_OFFSETS_CAPACITY, ALTER_PARTITION_REASSIGNMENTS_CAPACITY,
    ALTER_REPLICA_LOG_DIRS_CAPACITY, ALTER_USER_SCRAM_CREDENTIALS_CAPACITY, CREATE_ACLS_CAPACITY,
    CREATE_DELEGATION_TOKEN_CAPACITY, CREATE_PARTITIONS_CAPACITY, CREATE_TOPICS_CAPACITY,
    DELETE_ACLS_CAPACITY, DELETE_CONSUMER_GROUP_OFFSETS_CAPACITY, DELETE_CONSUMER_GROUPS_CAPACITY,
    DELETE_RECORDS_CAPACITY, DELETE_TOPICS_CAPACITY, DESCRIBE_ACLS_CAPACITY,
    DESCRIBE_CLIENT_QUOTAS_CAPACITY, DESCRIBE_CLUSTER_CAPACITY, DESCRIBE_CONFIGS_CAPACITY,
    DESCRIBE_CONSUMER_GROUPS_CAPACITY, DESCRIBE_DELEGATION_TOKENS_CAPACITY,
    DESCRIBE_FEATURES_CAPACITY, DESCRIBE_LOG_DIRS_CAPACITY, DESCRIBE_METADATA_QUORUM_CAPACITY,
    DESCRIBE_REPLICA_LOG_DIRS_CAPACITY, DESCRIBE_TOPICS_CAPACITY,
    DESCRIBE_USER_SCRAM_CREDENTIALS_CAPACITY, ELECT_LEADERS_CAPACITY,
    EXPIRE_DELEGATION_TOKEN_CAPACITY, INCREMENTAL_ALTER_CONFIGS_CAPACITY,
    LIST_CONSUMER_GROUP_OFFSETS_CAPACITY, LIST_CONSUMER_GROUPS_CAPACITY,
    LIST_PARTITION_REASSIGNMENTS_CAPACITY, REMOVE_CONSUMER_GROUP_MEMBERS_CAPACITY,
    REMOVE_RAFT_VOTER_CAPACITY, RENEW_DELEGATION_TOKEN_CAPACITY,
    alter_share_group_offsets::ALTER_SHARE_GROUP_OFFSETS_CAPACITY,
    completion::AdminCompletionNotifier,
    delete_share_group_offsets::DELETE_SHARE_GROUP_OFFSETS_CAPACITY,
    describe_share_group::DESCRIBE_SHARE_GROUP_CAPACITY,
    describe_streams_group::DESCRIBE_STREAMS_GROUP_CAPACITY,
    legacy_alter_configs::LEGACY_ALTER_CONFIGS_CAPACITY,
    list_client_metrics_resources::internal_api::LIST_CLIENT_METRICS_RESOURCES_CAPACITY,
    list_config_resources::LIST_CONFIG_RESOURCES_CAPACITY,
    list_share_group_offsets::LIST_SHARE_GROUP_OFFSETS_CAPACITY,
    unregister_broker::UNREGISTER_BROKER_CAPACITY, update_features::UPDATE_FEATURES_CAPACITY,
};

#[test]
fn group_offset_delete_is_included_in_the_closed_shared_capacity_equation() {
    assert_eq!(
        AdminCompletionNotifier::capacity_for_test().checked_sub(
            CREATE_TOPICS_CAPACITY
                + ABORT_PARTITION_TRANSACTION_CAPACITY
                + ADD_RAFT_VOTER_CAPACITY
                + DELETE_TOPICS_CAPACITY
                + DESCRIBE_CLUSTER_CAPACITY
                + CREATE_PARTITIONS_CAPACITY
                + DESCRIBE_TOPICS_CAPACITY
                + DESCRIBE_CONFIGS_CAPACITY
                + INCREMENTAL_ALTER_CONFIGS_CAPACITY
                + LEGACY_ALTER_CONFIGS_CAPACITY
                + LIST_CONSUMER_GROUP_OFFSETS_CAPACITY
                + DELETE_CONSUMER_GROUPS_CAPACITY
                + ALTER_CONSUMER_GROUP_OFFSETS_CAPACITY
                + ADMIN_LIST_OFFSETS_CAPACITY
                + LIST_PARTITION_REASSIGNMENTS_CAPACITY
                + ALTER_PARTITION_REASSIGNMENTS_CAPACITY
                + ELECT_LEADERS_CAPACITY
                + DELETE_RECORDS_CAPACITY
                + DELETE_SHARE_GROUP_OFFSETS_CAPACITY
                + LIST_SHARE_GROUP_OFFSETS_CAPACITY
                + ALTER_SHARE_GROUP_OFFSETS_CAPACITY
                + DESCRIBE_SHARE_GROUP_CAPACITY
                + DESCRIBE_STREAMS_GROUP_CAPACITY
                + DESCRIBE_CONSUMER_GROUPS_CAPACITY
                + DESCRIBE_FEATURES_CAPACITY
                + LIST_CONSUMER_GROUPS_CAPACITY
                + REMOVE_CONSUMER_GROUP_MEMBERS_CAPACITY
                + REMOVE_RAFT_VOTER_CAPACITY
                + DESCRIBE_LOG_DIRS_CAPACITY
                + DESCRIBE_REPLICA_LOG_DIRS_CAPACITY
                + ALTER_REPLICA_LOG_DIRS_CAPACITY
                + DESCRIBE_ACLS_CAPACITY
                + DESCRIBE_CLIENT_QUOTAS_CAPACITY
                + ALTER_CLIENT_QUOTAS_CAPACITY
                + ALTER_USER_SCRAM_CREDENTIALS_CAPACITY
                + DESCRIBE_USER_SCRAM_CREDENTIALS_CAPACITY
                + DESCRIBE_METADATA_QUORUM_CAPACITY
                + ADMIN_DESCRIBE_PRODUCERS_CAPACITY
                + ADMIN_DESCRIBE_TOPIC_PARTITIONS_CAPACITY
                + ADMIN_DESCRIBE_TRANSACTIONS_CAPACITY
                + ADMIN_FENCE_PRODUCERS_CAPACITY
                + ADMIN_LIST_TRANSACTIONS_CAPACITY
                + LIST_CLIENT_METRICS_RESOURCES_CAPACITY
                + UPDATE_FEATURES_CAPACITY
                + UNREGISTER_BROKER_CAPACITY
                + LIST_CONFIG_RESOURCES_CAPACITY
                + CREATE_ACLS_CAPACITY
                + CREATE_DELEGATION_TOKEN_CAPACITY
                + DESCRIBE_DELEGATION_TOKENS_CAPACITY
                + RENEW_DELEGATION_TOKEN_CAPACITY
                + EXPIRE_DELEGATION_TOKEN_CAPACITY
                + DELETE_ACLS_CAPACITY
        ),
        Some(DELETE_CONSUMER_GROUP_OFFSETS_CAPACITY)
    );
}

#[test]
fn group_offset_alter_is_included_in_the_closed_shared_capacity_equation() {
    assert_eq!(
        AdminCompletionNotifier::capacity_for_test().checked_sub(
            CREATE_TOPICS_CAPACITY
                + ABORT_PARTITION_TRANSACTION_CAPACITY
                + ADD_RAFT_VOTER_CAPACITY
                + DELETE_TOPICS_CAPACITY
                + DESCRIBE_CLUSTER_CAPACITY
                + CREATE_PARTITIONS_CAPACITY
                + DESCRIBE_TOPICS_CAPACITY
                + DESCRIBE_CONFIGS_CAPACITY
                + INCREMENTAL_ALTER_CONFIGS_CAPACITY
                + LEGACY_ALTER_CONFIGS_CAPACITY
                + LIST_CONSUMER_GROUP_OFFSETS_CAPACITY
                + DELETE_CONSUMER_GROUP_OFFSETS_CAPACITY
                + DELETE_CONSUMER_GROUPS_CAPACITY
                + ADMIN_LIST_OFFSETS_CAPACITY
                + LIST_PARTITION_REASSIGNMENTS_CAPACITY
                + ALTER_PARTITION_REASSIGNMENTS_CAPACITY
                + ELECT_LEADERS_CAPACITY
                + DELETE_RECORDS_CAPACITY
                + DELETE_SHARE_GROUP_OFFSETS_CAPACITY
                + LIST_SHARE_GROUP_OFFSETS_CAPACITY
                + ALTER_SHARE_GROUP_OFFSETS_CAPACITY
                + DESCRIBE_SHARE_GROUP_CAPACITY
                + DESCRIBE_STREAMS_GROUP_CAPACITY
                + DESCRIBE_CONSUMER_GROUPS_CAPACITY
                + DESCRIBE_FEATURES_CAPACITY
                + LIST_CONSUMER_GROUPS_CAPACITY
                + REMOVE_CONSUMER_GROUP_MEMBERS_CAPACITY
                + REMOVE_RAFT_VOTER_CAPACITY
                + DESCRIBE_LOG_DIRS_CAPACITY
                + DESCRIBE_REPLICA_LOG_DIRS_CAPACITY
                + ALTER_REPLICA_LOG_DIRS_CAPACITY
                + DESCRIBE_ACLS_CAPACITY
                + DESCRIBE_CLIENT_QUOTAS_CAPACITY
                + ALTER_CLIENT_QUOTAS_CAPACITY
                + ALTER_USER_SCRAM_CREDENTIALS_CAPACITY
                + DESCRIBE_USER_SCRAM_CREDENTIALS_CAPACITY
                + DESCRIBE_METADATA_QUORUM_CAPACITY
                + ADMIN_DESCRIBE_PRODUCERS_CAPACITY
                + ADMIN_DESCRIBE_TOPIC_PARTITIONS_CAPACITY
                + ADMIN_DESCRIBE_TRANSACTIONS_CAPACITY
                + ADMIN_FENCE_PRODUCERS_CAPACITY
                + ADMIN_LIST_TRANSACTIONS_CAPACITY
                + LIST_CLIENT_METRICS_RESOURCES_CAPACITY
                + UPDATE_FEATURES_CAPACITY
                + UNREGISTER_BROKER_CAPACITY
                + LIST_CONFIG_RESOURCES_CAPACITY
                + CREATE_ACLS_CAPACITY
                + CREATE_DELEGATION_TOKEN_CAPACITY
                + DESCRIBE_DELEGATION_TOKENS_CAPACITY
                + RENEW_DELEGATION_TOKEN_CAPACITY
                + EXPIRE_DELEGATION_TOKEN_CAPACITY
                + DELETE_ACLS_CAPACITY
        ),
        Some(ALTER_CONSUMER_GROUP_OFFSETS_CAPACITY)
    );
}
