//! Closed shared-admin capacity equations for destructive group-offset owners.

use super::{
    ADMIN_LIST_OFFSETS_CAPACITY, ALTER_CLIENT_QUOTAS_CAPACITY,
    ALTER_CONSUMER_GROUP_OFFSETS_CAPACITY, ALTER_PARTITION_REASSIGNMENTS_CAPACITY,
    ALTER_REPLICA_LOG_DIRS_CAPACITY, ALTER_USER_SCRAM_CREDENTIALS_CAPACITY, CREATE_ACLS_CAPACITY,
    CREATE_PARTITIONS_CAPACITY, CREATE_TOPICS_CAPACITY, DELETE_ACLS_CAPACITY,
    DELETE_CONSUMER_GROUP_OFFSETS_CAPACITY, DELETE_CONSUMER_GROUPS_CAPACITY,
    DELETE_RECORDS_CAPACITY, DELETE_TOPICS_CAPACITY, DESCRIBE_ACLS_CAPACITY,
    DESCRIBE_CLIENT_QUOTAS_CAPACITY, DESCRIBE_CLUSTER_CAPACITY, DESCRIBE_CONFIGS_CAPACITY,
    DESCRIBE_CONSUMER_GROUPS_CAPACITY, DESCRIBE_LOG_DIRS_CAPACITY, DESCRIBE_TOPICS_CAPACITY,
    DESCRIBE_USER_SCRAM_CREDENTIALS_CAPACITY, ELECT_LEADERS_CAPACITY,
    INCREMENTAL_ALTER_CONFIGS_CAPACITY, LIST_CONSUMER_GROUP_OFFSETS_CAPACITY,
    LIST_CONSUMER_GROUPS_CAPACITY, LIST_PARTITION_REASSIGNMENTS_CAPACITY,
    REMOVE_CONSUMER_GROUP_MEMBERS_CAPACITY, completion::AdminCompletionNotifier,
};

#[test]
fn group_offset_delete_is_included_in_the_closed_shared_capacity_equation() {
    assert_eq!(
        AdminCompletionNotifier::capacity_for_test().checked_sub(
            CREATE_TOPICS_CAPACITY
                + DELETE_TOPICS_CAPACITY
                + DESCRIBE_CLUSTER_CAPACITY
                + CREATE_PARTITIONS_CAPACITY
                + DESCRIBE_TOPICS_CAPACITY
                + DESCRIBE_CONFIGS_CAPACITY
                + INCREMENTAL_ALTER_CONFIGS_CAPACITY
                + LIST_CONSUMER_GROUP_OFFSETS_CAPACITY
                + DELETE_CONSUMER_GROUPS_CAPACITY
                + ALTER_CONSUMER_GROUP_OFFSETS_CAPACITY
                + ADMIN_LIST_OFFSETS_CAPACITY
                + LIST_PARTITION_REASSIGNMENTS_CAPACITY
                + ALTER_PARTITION_REASSIGNMENTS_CAPACITY
                + ELECT_LEADERS_CAPACITY
                + DELETE_RECORDS_CAPACITY
                + DESCRIBE_CONSUMER_GROUPS_CAPACITY
                + LIST_CONSUMER_GROUPS_CAPACITY
                + REMOVE_CONSUMER_GROUP_MEMBERS_CAPACITY
                + DESCRIBE_LOG_DIRS_CAPACITY
                + ALTER_REPLICA_LOG_DIRS_CAPACITY
                + DESCRIBE_ACLS_CAPACITY
                + DESCRIBE_CLIENT_QUOTAS_CAPACITY
                + ALTER_CLIENT_QUOTAS_CAPACITY
                + ALTER_USER_SCRAM_CREDENTIALS_CAPACITY
                + DESCRIBE_USER_SCRAM_CREDENTIALS_CAPACITY
                + CREATE_ACLS_CAPACITY
                + DELETE_ACLS_CAPACITY
        ),
        Some(DELETE_CONSUMER_GROUP_OFFSETS_CAPACITY)
    );
}

#[test]
fn group_offset_alter_is_included_in_the_closed_shared_capacity_equation() {
    assert_eq!(
        AdminCompletionNotifier::capacity_for_test().checked_sub(
            CREATE_TOPICS_CAPACITY
                + DELETE_TOPICS_CAPACITY
                + DESCRIBE_CLUSTER_CAPACITY
                + CREATE_PARTITIONS_CAPACITY
                + DESCRIBE_TOPICS_CAPACITY
                + DESCRIBE_CONFIGS_CAPACITY
                + INCREMENTAL_ALTER_CONFIGS_CAPACITY
                + LIST_CONSUMER_GROUP_OFFSETS_CAPACITY
                + DELETE_CONSUMER_GROUP_OFFSETS_CAPACITY
                + DELETE_CONSUMER_GROUPS_CAPACITY
                + ADMIN_LIST_OFFSETS_CAPACITY
                + LIST_PARTITION_REASSIGNMENTS_CAPACITY
                + ALTER_PARTITION_REASSIGNMENTS_CAPACITY
                + ELECT_LEADERS_CAPACITY
                + DELETE_RECORDS_CAPACITY
                + DESCRIBE_CONSUMER_GROUPS_CAPACITY
                + LIST_CONSUMER_GROUPS_CAPACITY
                + REMOVE_CONSUMER_GROUP_MEMBERS_CAPACITY
                + DESCRIBE_LOG_DIRS_CAPACITY
                + ALTER_REPLICA_LOG_DIRS_CAPACITY
                + DESCRIBE_ACLS_CAPACITY
                + DESCRIBE_CLIENT_QUOTAS_CAPACITY
                + ALTER_CLIENT_QUOTAS_CAPACITY
                + ALTER_USER_SCRAM_CREDENTIALS_CAPACITY
                + DESCRIBE_USER_SCRAM_CREDENTIALS_CAPACITY
                + CREATE_ACLS_CAPACITY
                + DELETE_ACLS_CAPACITY
        ),
        Some(ALTER_CONSUMER_GROUP_OFFSETS_CAPACITY)
    );
}
