//! Closed shared-admin capacity equations for concrete completion owners.

use super::{
    ABORT_PARTITION_TRANSACTION_CAPACITY, ADD_RAFT_VOTER_CAPACITY,
    ADMIN_DESCRIBE_PRODUCERS_CAPACITY, ADMIN_DESCRIBE_TOPIC_PARTITIONS_CAPACITY,
    ADMIN_DESCRIBE_TRANSACTIONS_CAPACITY, ADMIN_FENCE_PRODUCERS_CAPACITY,
    ADMIN_LIST_OFFSETS_CAPACITY, ADMIN_LIST_TRANSACTIONS_CAPACITY, ALTER_CLIENT_QUOTAS_CAPACITY,
    ALTER_CONSUMER_GROUP_OFFSETS_CAPACITY, ALTER_PARTITION_REASSIGNMENTS_CAPACITY,
    ALTER_REPLICA_LOG_DIRS_CAPACITY, ALTER_USER_SCRAM_CREDENTIALS_CAPACITY, CREATE_ACLS_CAPACITY,
    CREATE_DELEGATION_TOKEN_CAPACITY, CREATE_PARTITIONS_CAPACITY, CREATE_TOPICS_CAPACITY,
    DELETE_ACLS_CAPACITY, DELETE_CONSUMER_GROUP_OFFSETS_CAPACITY, DELETE_CONSUMER_GROUPS_CAPACITY,
    DELETE_RECORDS_CAPACITY, DELETE_TOPICS_CAPACITY, DESCRIBE_ACLS_CAPACITY,
    DESCRIBE_CLIENT_QUOTAS_CAPACITY, DESCRIBE_CLUSTER_CAPACITY, DESCRIBE_CONFIGS_CAPACITY,
    DESCRIBE_CONSUMER_GROUPS_CAPACITY, DESCRIBE_DELEGATION_TOKENS_CAPACITY,
    DESCRIBE_FEATURES_CAPACITY, DESCRIBE_LOG_DIRS_CAPACITY, DESCRIBE_METADATA_QUORUM_CAPACITY,
    DESCRIBE_REPLICA_LOG_DIRS_CAPACITY, DESCRIBE_TOPICS_CAPACITY,
    DESCRIBE_USER_SCRAM_CREDENTIALS_CAPACITY, ELECT_LEADERS_CAPACITY,
    EXPIRE_DELEGATION_TOKEN_CAPACITY, INCREMENTAL_ALTER_CONFIGS_CAPACITY,
    LIST_CONSUMER_GROUP_OFFSETS_CAPACITY, LIST_CONSUMER_GROUPS_CAPACITY,
    LIST_PARTITION_REASSIGNMENTS_CAPACITY, REMOVE_CONSUMER_GROUP_MEMBERS_CAPACITY,
    REMOVE_RAFT_VOTER_CAPACITY, RENEW_DELEGATION_TOKEN_CAPACITY,
    alter_share_group_offsets::ALTER_SHARE_GROUP_OFFSETS_CAPACITY,
    completion::AdminCompletionNotifier,
    delete_share_group_offsets::DELETE_SHARE_GROUP_OFFSETS_CAPACITY,
    describe_share_group::DESCRIBE_SHARE_GROUP_CAPACITY,
    describe_streams_group::DESCRIBE_STREAMS_GROUP_CAPACITY,
    legacy_alter_configs::LEGACY_ALTER_CONFIGS_CAPACITY,
    list_client_metrics_resources::internal_api::LIST_CLIENT_METRICS_RESOURCES_CAPACITY,
    list_config_resources::LIST_CONFIG_RESOURCES_CAPACITY,
    list_share_group_offsets::LIST_SHARE_GROUP_OFFSETS_CAPACITY,
    unregister_broker::UNREGISTER_BROKER_CAPACITY, update_features::UPDATE_FEATURES_CAPACITY,
};

const CLOSED_CAPACITY: usize = CREATE_TOPICS_CAPACITY
    + ABORT_PARTITION_TRANSACTION_CAPACITY
    + ADD_RAFT_VOTER_CAPACITY
    + REMOVE_RAFT_VOTER_CAPACITY
    + DELETE_TOPICS_CAPACITY
    + DESCRIBE_CLUSTER_CAPACITY
    + CREATE_PARTITIONS_CAPACITY
    + DESCRIBE_TOPICS_CAPACITY
    + DESCRIBE_CONFIGS_CAPACITY
    + INCREMENTAL_ALTER_CONFIGS_CAPACITY
    + LEGACY_ALTER_CONFIGS_CAPACITY
    + LIST_CONSUMER_GROUP_OFFSETS_CAPACITY
    + DELETE_CONSUMER_GROUP_OFFSETS_CAPACITY
    + DELETE_CONSUMER_GROUPS_CAPACITY
    + ALTER_CONSUMER_GROUP_OFFSETS_CAPACITY
    + ADMIN_LIST_OFFSETS_CAPACITY
    + LIST_PARTITION_REASSIGNMENTS_CAPACITY
    + ALTER_PARTITION_REASSIGNMENTS_CAPACITY
    + ELECT_LEADERS_CAPACITY
    + DELETE_RECORDS_CAPACITY
    + DELETE_SHARE_GROUP_OFFSETS_CAPACITY
    + LIST_SHARE_GROUP_OFFSETS_CAPACITY
    + ALTER_SHARE_GROUP_OFFSETS_CAPACITY
    + DESCRIBE_SHARE_GROUP_CAPACITY
    + DESCRIBE_STREAMS_GROUP_CAPACITY
    + DESCRIBE_CONSUMER_GROUPS_CAPACITY
    + DESCRIBE_FEATURES_CAPACITY
    + LIST_CONSUMER_GROUPS_CAPACITY
    + REMOVE_CONSUMER_GROUP_MEMBERS_CAPACITY
    + DESCRIBE_LOG_DIRS_CAPACITY
    + DESCRIBE_REPLICA_LOG_DIRS_CAPACITY
    + ALTER_REPLICA_LOG_DIRS_CAPACITY
    + DESCRIBE_ACLS_CAPACITY
    + DESCRIBE_CLIENT_QUOTAS_CAPACITY
    + ALTER_CLIENT_QUOTAS_CAPACITY
    + ALTER_USER_SCRAM_CREDENTIALS_CAPACITY
    + DESCRIBE_USER_SCRAM_CREDENTIALS_CAPACITY
    + DESCRIBE_METADATA_QUORUM_CAPACITY
    + ADMIN_DESCRIBE_PRODUCERS_CAPACITY
    + ADMIN_DESCRIBE_TOPIC_PARTITIONS_CAPACITY
    + ADMIN_DESCRIBE_TRANSACTIONS_CAPACITY
    + ADMIN_FENCE_PRODUCERS_CAPACITY
    + ADMIN_LIST_TRANSACTIONS_CAPACITY
    + LIST_CLIENT_METRICS_RESOURCES_CAPACITY
    + UPDATE_FEATURES_CAPACITY
    + UNREGISTER_BROKER_CAPACITY
    + LIST_CONFIG_RESOURCES_CAPACITY
    + CREATE_ACLS_CAPACITY
    + CREATE_DELEGATION_TOKEN_CAPACITY
    + DESCRIBE_DELEGATION_TOKENS_CAPACITY
    + RENEW_DELEGATION_TOKEN_CAPACITY
    + EXPIRE_DELEGATION_TOKEN_CAPACITY
    + DELETE_ACLS_CAPACITY;

#[test]
fn shared_capacity_is_the_sum_of_the_closed_admin_ticket_set() {
    assert_eq!(
        AdminCompletionNotifier::capacity_for_test(),
        CLOSED_CAPACITY
    );
}

fn capacity_without(excluded: usize) -> Option<usize> {
    AdminCompletionNotifier::capacity_for_test().checked_sub(CLOSED_CAPACITY - excluded)
}

#[test]
fn describe_topics_is_included_in_the_closed_shared_capacity_equation() {
    assert_eq!(
        capacity_without(DESCRIBE_TOPICS_CAPACITY),
        Some(DESCRIBE_TOPICS_CAPACITY)
    );
}

#[test]
fn create_partitions_is_included_in_the_closed_shared_capacity_equation() {
    assert_eq!(
        capacity_without(CREATE_PARTITIONS_CAPACITY),
        Some(CREATE_PARTITIONS_CAPACITY)
    );
}

#[test]
fn describe_configs_is_included_in_the_closed_shared_capacity_equation() {
    assert_eq!(
        capacity_without(DESCRIBE_CONFIGS_CAPACITY),
        Some(DESCRIBE_CONFIGS_CAPACITY)
    );
}

#[test]
fn incremental_alter_configs_is_included_in_the_closed_shared_capacity_equation() {
    assert_eq!(
        capacity_without(INCREMENTAL_ALTER_CONFIGS_CAPACITY),
        Some(INCREMENTAL_ALTER_CONFIGS_CAPACITY)
    );
}

#[test]
fn group_offsets_is_included_in_the_closed_shared_capacity_equation() {
    assert_eq!(
        capacity_without(LIST_CONSUMER_GROUP_OFFSETS_CAPACITY),
        Some(LIST_CONSUMER_GROUP_OFFSETS_CAPACITY)
    );
}

#[test]
fn partition_reassignment_listings_are_included_in_the_closed_shared_capacity_equation() {
    assert_eq!(
        capacity_without(LIST_PARTITION_REASSIGNMENTS_CAPACITY),
        Some(LIST_PARTITION_REASSIGNMENTS_CAPACITY)
    );
}

#[test]
fn partition_reassignment_alterations_are_included_in_the_closed_shared_capacity_equation() {
    assert_eq!(
        capacity_without(ALTER_PARTITION_REASSIGNMENTS_CAPACITY),
        Some(ALTER_PARTITION_REASSIGNMENTS_CAPACITY)
    );
}
