KafkaServer {
  org.apache.kafka.common.security.plain.PlainLoginModule required
  username="kafkars"
  password="kafkars-qualification-password"
  user_kafkars="kafkars-qualification-password";
  org.apache.kafka.common.security.scram.ScramLoginModule required;
};
