//! Startup capabilities and rollback joining for the native engine host.

use std::{
    sync::{Arc, mpsc::SyncSender},
    thread::JoinHandle,
};

use crate::{
    admin::{
        AbortPartitionTransactionAdmissionPort, AddRaftVoterAdmissionPort,
        AdminDescribeProducersAdmissionPort, AdminDescribeTopicPartitionsAdmissionPort,
        AdminDescribeTransactionsAdmissionPort, AdminFenceProducersAdmissionPort,
        AdminListOffsetsAdmissionPort, AdminListTransactionsAdmissionPort,
        AlterClientQuotasAdmissionPort, AlterConsumerGroupOffsetsAdmissionPort,
        AlterPartitionReassignmentsAdmissionPort, AlterReplicaLogDirsAdmissionPort,
        AlterUserScramCredentialsAdmissionPort, CreateAclsAdmissionPort,
        CreateDelegationTokenAdmissionPort, CreatePartitionsAdmissionPort,
        CreateTopicsAdmissionPort, DeleteAclsAdmissionPort,
        DeleteConsumerGroupOffsetsAdmissionPort, DeleteConsumerGroupsAdmissionPort,
        DeleteRecordsAdmissionPort, DeleteTopicsAdmissionPort, DescribeAclsAdmissionPort,
        DescribeClientQuotasAdmissionPort, DescribeClusterAdmissionPort,
        DescribeConfigsAdmissionPort, DescribeConsumerGroupsAdmissionPort,
        DescribeDelegationTokensAdmissionPort, DescribeFeaturesAdmissionPort,
        DescribeLogDirsAdmissionPort, DescribeMetadataQuorumAdmissionPort,
        DescribeReplicaLogDirsAdmissionPort, DescribeTopicsAdmissionPort,
        DescribeUserScramCredentialsAdmissionPort, ElectLeadersAdmissionPort,
        ExpireDelegationTokenAdmissionPort, IncrementalAlterConfigsAdmissionPort,
        LegacyAlterConfigsAdmissionPort, ListConsumerGroupOffsetsAdmissionPort,
        ListPartitionReassignmentsAdmissionPort, RemoveConsumerGroupMembersAdmissionPort,
        RemoveRaftVoterAdmissionPort, RenewDelegationTokenAdmissionPort,
        alter_share_group_offsets::AlterShareGroupOffsetsAdmissionPort,
        delete_share_group_offsets::DeleteShareGroupOffsetsAdmissionPort,
        describe_share_group::DescribeShareGroupAdmissionPort,
        describe_streams_group::DescribeStreamsGroupAdmissionPort,
        list_client_metrics_resources::internal_api::ListClientMetricsResourcesAdmissionPort,
        list_config_resources::ListConfigResourcesAdmissionPort,
        list_share_group_offsets::ListShareGroupOffsetsAdmissionPort,
        unregister_broker::UnregisterBrokerAdmissionPort,
        update_features::UpdateFeaturesAdmissionPort,
    },
    clock::MonotonicClock,
    consumer::{AssignedConsumerPort, GroupConsumerPort},
    producer::ingress::ProducerAdmissionPort,
    transaction::TransactionInitializationAdmissionPort,
};

use super::{EngineHostControl, EngineHostResources, EngineLifecycle, EngineStartError};

pub(crate) struct StartedEngineHost {
    pub(crate) metrics: crate::driver::owner::observation::DriverObservationHandle,
    pub(crate) admission: ProducerAdmissionPort,
    pub(crate) abort_partition_transaction_admission: AbortPartitionTransactionAdmissionPort,
    pub(crate) add_raft_voter_admission: AddRaftVoterAdmissionPort,
    pub(crate) remove_raft_voter_admission: RemoveRaftVoterAdmissionPort,
    pub(crate) create_topics_admission: CreateTopicsAdmissionPort,
    pub(crate) create_acls_admission: CreateAclsAdmissionPort,
    pub(crate) create_delegation_token_admission: CreateDelegationTokenAdmissionPort,
    pub(crate) describe_delegation_tokens_admission: DescribeDelegationTokensAdmissionPort,
    pub(crate) renew_delegation_token_admission: RenewDelegationTokenAdmissionPort,
    pub(crate) expire_delegation_token_admission: ExpireDelegationTokenAdmissionPort,
    pub(crate) delete_acls_admission: DeleteAclsAdmissionPort,
    pub(crate) delete_topics_admission: DeleteTopicsAdmissionPort,
    pub(crate) delete_consumer_groups_admission: DeleteConsumerGroupsAdmissionPort,
    pub(crate) delete_records_admission: DeleteRecordsAdmissionPort,
    pub(crate) describe_acls_admission: DescribeAclsAdmissionPort,
    pub(crate) describe_client_quotas_admission: DescribeClientQuotasAdmissionPort,
    pub(crate) alter_client_quotas_admission: AlterClientQuotasAdmissionPort,
    pub(crate) alter_user_scram_credentials_admission: AlterUserScramCredentialsAdmissionPort,
    pub(crate) update_features_admission: UpdateFeaturesAdmissionPort,
    pub(crate) unregister_broker_admission: UnregisterBrokerAdmissionPort,
    pub(crate) describe_user_scram_credentials_admission: DescribeUserScramCredentialsAdmissionPort,
    pub(crate) describe_metadata_quorum_admission: DescribeMetadataQuorumAdmissionPort,
    pub(crate) describe_producers_admission: AdminDescribeProducersAdmissionPort,
    pub(crate) describe_topic_partitions_admission: AdminDescribeTopicPartitionsAdmissionPort,
    pub(crate) describe_transactions_admission: AdminDescribeTransactionsAdmissionPort,
    pub(crate) fence_producers_admission: AdminFenceProducersAdmissionPort,
    pub(crate) list_transactions_admission: AdminListTransactionsAdmissionPort,
    pub(crate) list_client_metrics_resources_admission: ListClientMetricsResourcesAdmissionPort,
    pub(crate) list_config_resources_admission: ListConfigResourcesAdmissionPort,
    pub(crate) describe_cluster_admission: DescribeClusterAdmissionPort,
    pub(crate) describe_consumer_groups_admission: DescribeConsumerGroupsAdmissionPort,
    pub(crate) describe_features_admission: DescribeFeaturesAdmissionPort,
    pub(crate) describe_log_dirs_admission: DescribeLogDirsAdmissionPort,
    pub(crate) describe_replica_log_dirs_admission: DescribeReplicaLogDirsAdmissionPort,
    pub(crate) create_partitions_admission: CreatePartitionsAdmissionPort,
    pub(crate) describe_topics_admission: DescribeTopicsAdmissionPort,
    pub(crate) describe_configs_admission: DescribeConfigsAdmissionPort,
    pub(crate) incremental_alter_configs_admission: IncrementalAlterConfigsAdmissionPort,
    pub(crate) legacy_alter_configs_admission: LegacyAlterConfigsAdmissionPort,
    pub(crate) list_consumer_group_offsets_admission: ListConsumerGroupOffsetsAdmissionPort,
    pub(crate) list_consumer_groups_admission: crate::admin::ListConsumerGroupsAdmissionPort,
    pub(crate) delete_consumer_group_offsets_admission: DeleteConsumerGroupOffsetsAdmissionPort,
    pub(crate) delete_share_group_offsets_admission: DeleteShareGroupOffsetsAdmissionPort,
    pub(crate) list_share_group_offsets_admission: ListShareGroupOffsetsAdmissionPort,
    pub(crate) alter_share_group_offsets_admission: AlterShareGroupOffsetsAdmissionPort,
    pub(crate) describe_share_group_admission: DescribeShareGroupAdmissionPort,
    pub(crate) describe_streams_group_admission: DescribeStreamsGroupAdmissionPort,
    pub(crate) alter_consumer_group_offsets_admission: AlterConsumerGroupOffsetsAdmissionPort,
    pub(crate) list_offsets_admission: AdminListOffsetsAdmissionPort,
    pub(crate) list_partition_reassignments_admission: ListPartitionReassignmentsAdmissionPort,
    pub(crate) alter_partition_reassignments_admission: AlterPartitionReassignmentsAdmissionPort,
    pub(crate) alter_replica_log_dirs_admission: AlterReplicaLogDirsAdmissionPort,
    pub(crate) elect_leaders_admission: ElectLeadersAdmissionPort,
    pub(crate) remove_consumer_group_members_admission: RemoveConsumerGroupMembersAdmissionPort,
    pub(crate) assigned_consumer: AssignedConsumerPort,
    pub(crate) group_consumer: GroupConsumerPort,
    pub(crate) transaction_initialization: TransactionInitializationAdmissionPort,
    pub(crate) clock: Arc<MonotonicClock>,
    pub(crate) control: Arc<EngineHostControl>,
    pub(crate) lifecycle: Arc<EngineLifecycle>,
}

pub(super) fn cancel_start(
    sender: SyncSender<EngineHostResources>,
    handle: JoinHandle<()>,
    error: EngineStartError,
) -> Result<StartedEngineHost, EngineStartError> {
    drop(sender);
    join_cancelled(handle);
    Err(error)
}

pub(super) fn join_cancelled(handle: JoinHandle<()>) {
    let _join_result = handle.join();
}
