//! Internal terminal diagnostics for concrete engine-host owners.

use crate::{
    admin::{
        AdminListOffsetsHostError, AlterConsumerGroupOffsetsHostError,
        AlterPartitionReassignmentsHostError, AlterReplicaLogDirsHostError, CreateAclsHostError,
        CreatePartitionsHostError, CreateTopicsHostError, DeleteAclsHostError,
        DeleteConsumerGroupOffsetsHostError, DeleteConsumerGroupsHostError, DeleteRecordsHostError,
        DeleteTopicsHostError, DescribeAclsHostError, DescribeClusterHostError,
        DescribeConfigsHostError, DescribeConsumerGroupsHostError, DescribeLogDirsHostError,
        DescribeTopicsHostError, ElectLeadersHostError, IncrementalAlterConfigsHostError,
        ListConsumerGroupOffsetsHostError, ListConsumerGroupsHostError,
        ListPartitionReassignmentsHostError, RemoveConsumerGroupMembersHostError,
    },
    clock::ClockError,
    completion::{CompletionRegistryError, NotifierJoinError},
    consumer::{
        AssignedConsumerFaultKind, AssignedConsumerOwnerError, AssignedConsumerRecoveryReport,
        GroupConsumerHostError,
    },
    driver::{
        CreatePartitionsCompletionFailure, CreateTopicsCompletionFailure,
        DeleteTopicsCompletionFailure, DescribeClusterCompletionFailure,
        DescribeConfigsCompletionFailure, DescribeTopicsCompletionFailure, DriverOwnerError,
        IncrementalAlterConfigsCompletionFailure, ProduceCompletionFailure,
        ProducerIdentityCompletionFailure,
    },
    producer::{
        ProducerHostInvariantError, ProducerIdentityHandoffError,
        execution::PreparedProduceHandoffError, execution_stop::ProducerExecutionStopError,
        ingress::ProducerShardTerminalError,
    },
    transaction::TransactionInitializationHostError,
};

#[derive(Debug)]
pub(crate) enum EngineHostError {
    Clock(ClockError),
    Producer(ProducerHostInvariantError),
    ProducerHandoff(PreparedProduceHandoffError),
    ProducerIdentityHandoff(ProducerIdentityHandoffError),
    ProduceCompletion(ProduceCompletionFailure),
    ProducerIdentityCompletion(ProducerIdentityCompletionFailure),
    ProducerStop(ProducerExecutionStopError),
    ProducerCleanup(ProducerShardTerminalError),
    ProducerLockPoisoned,
    AssignedConsumer(AssignedConsumerOwnerError),
    AssignedConsumerFault(AssignedConsumerFaultKind),
    AssignedConsumerLockPoisoned,
    AssignedConsumerOwnerMissing,
    AssignedConsumerCloseIncomplete,
    AssignedConsumerUnsettled(usize),
    AssignedConsumerRecovery(Box<AssignedConsumerRecoveryReport>),
    AssignedConsumerCompletion(CompletionRegistryError),
    GroupConsumer(GroupConsumerHostError),
    GroupConsumerLockPoisoned,
    GroupConsumerRecvNotifierUnavailable,
    TransactionInitialization(TransactionInitializationHostError),
    TransactionInitializationLockPoisoned,
    CreateTopics(CreateTopicsHostError),
    CreateTopicsCompletion(CreateTopicsCompletionFailure),
    CreateTopicsLockPoisoned,
    DeleteTopics(DeleteTopicsHostError),
    DeleteTopicsCompletion(DeleteTopicsCompletionFailure),
    DeleteTopicsLockPoisoned,
    DeleteRecords(DeleteRecordsHostError),
    DeleteRecordsLockPoisoned,
    DescribeAcls(DescribeAclsHostError),
    DescribeAclsLockPoisoned,
    CreateAcls(CreateAclsHostError),
    CreateAclsLockPoisoned,
    DeleteAcls(DeleteAclsHostError),
    DeleteAclsLockPoisoned,
    DescribeCluster(DescribeClusterHostError),
    DescribeClusterCompletion(DescribeClusterCompletionFailure),
    DescribeClusterLockPoisoned,
    DescribeConsumerGroups(DescribeConsumerGroupsHostError),
    DescribeConsumerGroupsLockPoisoned,
    DescribeLogDirs(DescribeLogDirsHostError),
    DescribeLogDirsLockPoisoned,
    AlterReplicaLogDirs(AlterReplicaLogDirsHostError),
    AlterReplicaLogDirsLockPoisoned,
    CreatePartitions(CreatePartitionsHostError),
    CreatePartitionsCompletion(CreatePartitionsCompletionFailure),
    CreatePartitionsLockPoisoned,
    DescribeTopics(DescribeTopicsHostError),
    DescribeTopicsCompletion(DescribeTopicsCompletionFailure),
    DescribeTopicsLockPoisoned,
    DescribeConfigs(DescribeConfigsHostError),
    DescribeConfigsCompletion(DescribeConfigsCompletionFailure),
    DescribeConfigsLockPoisoned,
    IncrementalAlterConfigs(IncrementalAlterConfigsHostError),
    IncrementalAlterConfigsCompletion(IncrementalAlterConfigsCompletionFailure),
    IncrementalAlterConfigsLockPoisoned,
    ListConsumerGroupOffsets(ListConsumerGroupOffsetsHostError),
    ListConsumerGroupOffsetsLockPoisoned,
    ListConsumerGroups(ListConsumerGroupsHostError),
    ListConsumerGroupsLockPoisoned,
    DeleteConsumerGroupOffsets(DeleteConsumerGroupOffsetsHostError),
    DeleteConsumerGroupOffsetsLockPoisoned,
    DeleteConsumerGroups(DeleteConsumerGroupsHostError),
    DeleteConsumerGroupsLockPoisoned,
    AlterConsumerGroupOffsets(AlterConsumerGroupOffsetsHostError),
    AlterConsumerGroupOffsetsLockPoisoned,
    AdminListOffsets(AdminListOffsetsHostError),
    AdminListOffsetsLockPoisoned,
    ListPartitionReassignments(ListPartitionReassignmentsHostError),
    ListPartitionReassignmentsLockPoisoned,
    AlterPartitionReassignments(AlterPartitionReassignmentsHostError),
    AlterPartitionReassignmentsLockPoisoned,
    ElectLeaders(ElectLeadersHostError),
    ElectLeadersLockPoisoned,
    RemoveConsumerGroupMembers(RemoveConsumerGroupMembersHostError),
    RemoveConsumerGroupMembersLockPoisoned,
    AdminCompletion(CompletionRegistryError),
    Driver(DriverOwnerError),
    DriverOwnerMissing,
    DriverStopped,
    TrackedProduceCallsRemain(usize),
    TrackedProducerIdentityCallsRemain(usize),
    TrackedCreateTopicsCallsRemain(usize),
    TrackedDeleteTopicsCallsRemain(usize),
    DescribeClusterCallsRemain(usize),
    TrackedCreatePartitionsCallsRemain(usize),
    DescribeTopicsCallsRemain(usize),
    DescribeConfigsCallsRemain(usize),
    IncrementalAlterConfigsCallsRemain(usize),
    HostPanicked,
    Notifier(NotifierJoinError),
    Recovery {
        primary: Box<EngineHostError>,
        cleanup: Box<EngineHostError>,
    },
    #[cfg(test)]
    ForcedTestFailure,
}

impl EngineHostError {
    pub(in crate::engine_host) fn with_cleanup(self, cleanup: Self) -> Self {
        Self::Recovery {
            primary: Box::new(self),
            cleanup: Box::new(cleanup),
        }
    }
}

impl std::error::Error for EngineHostError {
    fn source(&self) -> Option<&(dyn std::error::Error + 'static)> {
        match self {
            Self::Recovery { primary, .. } => Some(primary),
            _ => None,
        }
    }
}
