//! Internal terminal diagnostics for concrete engine-host owners.

use crate::{
    admin::{
        AbortPartitionTransactionHostError, AddRaftVoterHostError, AdminDescribeProducersHostError,
        AdminDescribeTopicPartitionsHostError, AdminDescribeTransactionsHostError,
        AdminFenceProducersHostError, AdminListOffsetsHostError, AdminListTransactionsHostError,
        AlterClientQuotasHostError, AlterConsumerGroupOffsetsHostError,
        AlterPartitionReassignmentsHostError, AlterReplicaLogDirsHostError,
        AlterUserScramCredentialsHostError, CreateAclsHostError, CreateDelegationTokenHostError,
        CreatePartitionsHostError, CreateTopicsHostError, DeleteAclsHostError,
        DeleteConsumerGroupOffsetsHostError, DeleteConsumerGroupsHostError, DeleteRecordsHostError,
        DeleteTopicsHostError, DescribeAclsHostError, DescribeClientQuotasHostError,
        DescribeClusterHostError, DescribeConfigsHostError, DescribeConsumerGroupsHostError,
        DescribeDelegationTokensHostError, DescribeFeaturesHostError, DescribeLogDirsHostError,
        DescribeMetadataQuorumHostError, DescribeReplicaLogDirsHostError, DescribeTopicsHostError,
        DescribeUserScramCredentialsHostError, ElectLeadersHostError,
        ExpireDelegationTokenHostError, IncrementalAlterConfigsHostError,
        LegacyAlterConfigsHostError, ListConsumerGroupOffsetsHostError,
        ListConsumerGroupsHostError, ListPartitionReassignmentsHostError,
        RemoveConsumerGroupMembersHostError, RemoveRaftVoterHostError,
        RenewDelegationTokenHostError, alter_share_group_offsets::AlterShareGroupOffsetsHostError,
        delete_share_group_offsets::DeleteShareGroupOffsetsHostError,
        describe_share_group::DescribeShareGroupHostError,
        describe_streams_group::DescribeStreamsGroupHostError,
        list_client_metrics_resources::internal_api::ListClientMetricsResourcesHostError,
        list_config_resources::ListConfigResourcesHostError,
        list_share_group_offsets::ListShareGroupOffsetsHostError,
        unregister_broker::UnregisterBrokerHostError, update_features::UpdateFeaturesHostError,
    },
    clock::ClockError,
    completion::{CompletionRegistryError, NotifierJoinError},
    consumer::{
        AssignedConsumerFaultKind, AssignedConsumerOwnerError, AssignedConsumerRecoveryReport,
        GroupConsumerHostError,
    },
    driver::{
        CreatePartitionsCompletionFailure, CreateTopicsCompletionFailure,
        DeleteTopicsCompletionFailure, DescribeClusterCompletionFailure,
        DescribeConfigsCompletionFailure, DescribeTopicsCompletionFailure, DriverOwnerError,
        IncrementalAlterConfigsCompletionFailure, ProduceCompletionFailure,
        ProducerIdentityCompletionFailure,
    },
    producer::{
        ProducerHostInvariantError, ProducerIdentityHandoffError,
        execution::PreparedProduceHandoffError, execution_stop::ProducerExecutionStopError,
        ingress::ProducerShardTerminalError,
    },
    transaction::TransactionInitializationHostError,
};

#[derive(Debug)]
pub(crate) enum EngineHostError {
    Clock(ClockError),
    Producer(ProducerHostInvariantError),
    ProducerHandoff(PreparedProduceHandoffError),
    ProducerIdentityHandoff(ProducerIdentityHandoffError),
    ProduceCompletion(ProduceCompletionFailure),
    ProducerIdentityCompletion(ProducerIdentityCompletionFailure),
    ProducerStop(ProducerExecutionStopError),
    ProducerCleanup(ProducerShardTerminalError),
    ProducerLockPoisoned,
    AssignedConsumer(AssignedConsumerOwnerError),
    AssignedConsumerFault(AssignedConsumerFaultKind),
    AssignedConsumerLockPoisoned,
    AssignedConsumerOwnerMissing,
    AssignedConsumerCloseIncomplete,
    AssignedConsumerUnsettled(usize),
    AssignedConsumerRecovery(Box<AssignedConsumerRecoveryReport>),
    AssignedConsumerCompletion(CompletionRegistryError),
    GroupConsumer(GroupConsumerHostError),
    GroupConsumerLockPoisoned,
    GroupConsumerRecvNotifierUnavailable,
    TransactionInitialization(TransactionInitializationHostError),
    TransactionInitializationLockPoisoned,
    CreateTopics(CreateTopicsHostError),
    CreateTopicsCompletion(CreateTopicsCompletionFailure),
    CreateTopicsLockPoisoned,
    DeleteTopics(DeleteTopicsHostError),
    DeleteTopicsCompletion(DeleteTopicsCompletionFailure),
    DeleteTopicsLockPoisoned,
    DeleteRecords(DeleteRecordsHostError),
    DeleteRecordsLockPoisoned,
    AbortPartitionTransaction(AbortPartitionTransactionHostError),
    AbortPartitionTransactionLockPoisoned,
    AdminDescribeProducers(AdminDescribeProducersHostError),
    AdminDescribeProducersLockPoisoned,
    AdminDescribeTopicPartitions(AdminDescribeTopicPartitionsHostError),
    AdminDescribeTopicPartitionsLockPoisoned,
    AdminDescribeTransactions(AdminDescribeTransactionsHostError),
    AdminDescribeTransactionsLockPoisoned,
    AdminFenceProducers(AdminFenceProducersHostError),
    AdminFenceProducersLockPoisoned,
    AdminListTransactions(AdminListTransactionsHostError),
    AdminListTransactionsLockPoisoned,
    ListClientMetricsResources(ListClientMetricsResourcesHostError),
    ListClientMetricsResourcesLockPoisoned,
    ListConfigResources(ListConfigResourcesHostError),
    ListConfigResourcesLockPoisoned,
    DescribeAcls(DescribeAclsHostError),
    DescribeAclsLockPoisoned,
    DescribeClientQuotas(DescribeClientQuotasHostError),
    DescribeClientQuotasLockPoisoned,
    AlterClientQuotas(AlterClientQuotasHostError),
    AlterClientQuotasLockPoisoned,
    AlterUserScramCredentials(AlterUserScramCredentialsHostError),
    AlterUserScramCredentialsLockPoisoned,
    UpdateFeatures(UpdateFeaturesHostError),
    UpdateFeaturesLockPoisoned,
    DescribeUserScramCredentials(DescribeUserScramCredentialsHostError),
    DescribeUserScramCredentialsLockPoisoned,
    DescribeMetadataQuorum(DescribeMetadataQuorumHostError),
    DescribeMetadataQuorumLockPoisoned,
    CreateAcls(CreateAclsHostError),
    CreateAclsLockPoisoned,
    CreateDelegationToken(CreateDelegationTokenHostError),
    CreateDelegationTokenLockPoisoned,
    DescribeDelegationTokens(DescribeDelegationTokensHostError),
    DescribeDelegationTokensLockPoisoned,
    RenewDelegationToken(RenewDelegationTokenHostError),
    RenewDelegationTokenLockPoisoned,
    ExpireDelegationToken(ExpireDelegationTokenHostError),
    ExpireDelegationTokenLockPoisoned,
    DeleteAcls(DeleteAclsHostError),
    DeleteAclsLockPoisoned,
    DescribeCluster(DescribeClusterHostError),
    DescribeClusterCompletion(DescribeClusterCompletionFailure),
    DescribeClusterLockPoisoned,
    DescribeConsumerGroups(DescribeConsumerGroupsHostError),
    DescribeConsumerGroupsLockPoisoned,
    DescribeFeatures(DescribeFeaturesHostError),
    DescribeFeaturesLockPoisoned,
    UnregisterBroker(UnregisterBrokerHostError),
    UnregisterBrokerLockPoisoned,
    AddRaftVoter(AddRaftVoterHostError),
    AddRaftVoterLockPoisoned,
    RemoveRaftVoter(RemoveRaftVoterHostError),
    RemoveRaftVoterLockPoisoned,
    DescribeLogDirs(DescribeLogDirsHostError),
    DescribeLogDirsLockPoisoned,
    DescribeReplicaLogDirs(DescribeReplicaLogDirsHostError),
    DescribeReplicaLogDirsLockPoisoned,
    AlterReplicaLogDirs(AlterReplicaLogDirsHostError),
    AlterReplicaLogDirsLockPoisoned,
    CreatePartitions(CreatePartitionsHostError),
    CreatePartitionsCompletion(CreatePartitionsCompletionFailure),
    CreatePartitionsLockPoisoned,
    DescribeTopics(DescribeTopicsHostError),
    DescribeTopicsCompletion(DescribeTopicsCompletionFailure),
    DescribeTopicsLockPoisoned,
    DescribeConfigs(DescribeConfigsHostError),
    DescribeConfigsCompletion(DescribeConfigsCompletionFailure),
    DescribeConfigsLockPoisoned,
    IncrementalAlterConfigs(IncrementalAlterConfigsHostError),
    IncrementalAlterConfigsCompletion(IncrementalAlterConfigsCompletionFailure),
    IncrementalAlterConfigsLockPoisoned,
    LegacyAlterConfigs(LegacyAlterConfigsHostError),
    LegacyAlterConfigsLockPoisoned,
    ListConsumerGroupOffsets(ListConsumerGroupOffsetsHostError),
    ListConsumerGroupOffsetsLockPoisoned,
    ListConsumerGroups(ListConsumerGroupsHostError),
    ListConsumerGroupsLockPoisoned,
    DeleteConsumerGroupOffsets(DeleteConsumerGroupOffsetsHostError),
    DeleteConsumerGroupOffsetsLockPoisoned,
    DeleteShareGroupOffsets(DeleteShareGroupOffsetsHostError),
    DeleteShareGroupOffsetsLockPoisoned,
    ListShareGroupOffsets(ListShareGroupOffsetsHostError),
    ListShareGroupOffsetsLockPoisoned,
    AlterShareGroupOffsets(AlterShareGroupOffsetsHostError),
    AlterShareGroupOffsetsLockPoisoned,
    DescribeShareGroup(DescribeShareGroupHostError),
    DescribeShareGroupLockPoisoned,
    DescribeStreamsGroup(DescribeStreamsGroupHostError),
    DescribeStreamsGroupLockPoisoned,
    DeleteConsumerGroups(DeleteConsumerGroupsHostError),
    DeleteConsumerGroupsLockPoisoned,
    AlterConsumerGroupOffsets(AlterConsumerGroupOffsetsHostError),
    AlterConsumerGroupOffsetsLockPoisoned,
    AdminListOffsets(AdminListOffsetsHostError),
    AdminListOffsetsLockPoisoned,
    ListPartitionReassignments(ListPartitionReassignmentsHostError),
    ListPartitionReassignmentsLockPoisoned,
    AlterPartitionReassignments(AlterPartitionReassignmentsHostError),
    AlterPartitionReassignmentsLockPoisoned,
    ElectLeaders(ElectLeadersHostError),
    ElectLeadersLockPoisoned,
    RemoveConsumerGroupMembers(RemoveConsumerGroupMembersHostError),
    RemoveConsumerGroupMembersLockPoisoned,
    AdminCompletion(CompletionRegistryError),
    Driver(DriverOwnerError),
    DriverOwnerMissing,
    DriverStopped,
    TrackedProduceCallsRemain(usize),
    TrackedProducerIdentityCallsRemain(usize),
    TrackedCreateTopicsCallsRemain(usize),
    TrackedDeleteTopicsCallsRemain(usize),
    DescribeClusterCallsRemain(usize),
    TrackedCreatePartitionsCallsRemain(usize),
    DescribeTopicsCallsRemain(usize),
    DescribeConfigsCallsRemain(usize),
    IncrementalAlterConfigsCallsRemain(usize),
    HostPanicked,
    Notifier(NotifierJoinError),
    Recovery {
        primary: Box<EngineHostError>,
        cleanup: Box<EngineHostError>,
    },
    #[cfg(test)]
    ForcedTestFailure,
}

impl EngineHostError {
    pub(in crate::engine_host) fn with_cleanup(self, cleanup: Self) -> Self {
        Self::Recovery {
            primary: Box::new(self),
            cleanup: Box::new(cleanup),
        }
    }
}

impl std::error::Error for EngineHostError {
    fn source(&self) -> Option<&(dyn std::error::Error + 'static)> {
        match self {
            Self::Recovery { primary, .. } => Some(primary),
            _ => None,
        }
    }
}
