//! Exact static policy expected for the bounded group registry.

pub(super) const ROOT: &str = "crates/kafka-client-engine/src/consumer/group/";
pub(super) const REGISTRY_PATH: &str = "crates/kafka-client-engine/src/consumer/group/registry.rs";
pub(super) const ENTRY_PATH: &str =
    "crates/kafka-client-engine/src/consumer/group/registry_entry.rs";
pub(super) const HOST_START_METHOD: &str = "start_group_offset_commit_host";
pub(super) const MIRRORS: &[(&str, &str)] = &[
    ("registry.rs", "registry_test.rs"),
    ("registry_entry.rs", "registry_entry_test.rs"),
    ("registry_commit.rs", "registry_commit_test.rs"),
    ("registry_close.rs", "registry_close_test.rs"),
    ("registry_host.rs", "registry_host_test.rs"),
    ("registry_session.rs", "registry_session_test.rs"),
];
pub(super) const REGISTRY_FIELDS: &[(&str, &[&str])] = &[
    (
        "entries",
        &[
            "registry.rs",
            "classic_group_heartbeat_prepare.rs",
            "classic_group_heartbeat_recovery.rs",
            "classic_group_heartbeat_settlement.rs",
            "classic_group_heartbeat_submission.rs",
            "classic_group_join_execution.rs",
            "classic_group_join_settlement.rs",
            "classic_group_rediscovery_execution.rs",
            "classic_group_rediscovery_recovery.rs",
            "classic_group_recovery.rs",
            "classic_group_rejoin_due.rs",
            "classic_group_sync_settlement.rs",
            "classic_group_sync_submission.rs",
            "registry_close.rs",
            "registry_cycle.rs",
            "registry_membership.rs",
            "registry_session.rs",
        ],
    ),
    ("next_group_id", &["registry.rs"]),
    ("retained_group_bytes", &["registry.rs"]),
    ("accepting", &["registry.rs", "registry_close.rs"]),
    (
        "offset_commits",
        &[
            "registry.rs",
            "registry_commit.rs",
            "registry_close.rs",
            "registry_host.rs",
        ],
    ),
    (
        "join_calls",
        &[
            "registry.rs",
            "classic_group_join_execution.rs",
            "classic_group_join_settlement.rs",
            "classic_group_recovery.rs",
        ],
    ),
    (
        "sync_calls",
        &[
            "registry.rs",
            "classic_group_sync_settlement.rs",
            "classic_group_sync_submission.rs",
            "classic_group_recovery.rs",
        ],
    ),
    (
        "heartbeat_calls",
        &[
            "registry.rs",
            "classic_group_heartbeat_recovery.rs",
            "classic_group_heartbeat_settlement.rs",
            "classic_group_heartbeat_submission.rs",
        ],
    ),
    (
        "coordinator_invalidations",
        &[
            "registry.rs",
            "classic_group_heartbeat_settlement.rs",
            "classic_group_join_settlement.rs",
            "classic_group_rediscovery_execution.rs",
            "classic_group_rediscovery_recovery.rs",
            "classic_group_sync_settlement.rs",
        ],
    ),
    (
        "coordinator_invalidation_shutdown_recovery",
        &["registry.rs", "classic_group_rediscovery_recovery.rs"],
    ),
    (
        "join_shutdown_recovery",
        &["registry.rs", "classic_group_recovery.rs"],
    ),
    (
        "sync_shutdown_recovery",
        &["registry.rs", "classic_group_recovery.rs"],
    ),
    (
        "heartbeat_shutdown_recovery",
        &["registry.rs", "classic_group_heartbeat_recovery.rs"],
    ),
    (
        "join_recovery_fault",
        &["registry.rs", "classic_group_recovery.rs"],
    ),
    (
        "sync_recovery_fault",
        &["registry.rs", "classic_group_recovery.rs"],
    ),
    (
        "heartbeat_recovery_fault",
        &["registry.rs", "classic_group_heartbeat_recovery.rs"],
    ),
];
pub(super) const ENTRY_FIELDS: &[(&str, &[&str])] = &[
    ("state", &["registry_close.rs"]),
    (
        "fault",
        &[
            "registry.rs",
            "registry_entry.rs",
            "classic_group_heartbeat_prepare.rs",
            "classic_group_heartbeat_recovery.rs",
            "classic_group_heartbeat_settlement.rs",
            "classic_group_heartbeat_submission.rs",
            "classic_group_join_execution.rs",
            "classic_group_join_settlement.rs",
            "classic_group_rediscovery_execution.rs",
            "classic_group_rediscovery_recovery.rs",
            "classic_group_rediscovery_transfer.rs",
            "classic_group_recovery.rs",
            "classic_group_rejoin_due.rs",
            "classic_group_sync_submission.rs",
            "classic_group_sync_settlement.rs",
            "classic_group_sync_install.rs",
            "classic_group_sync_interpret.rs",
            "registry_membership.rs",
        ],
    ),
];
pub(super) const REGISTRY_DECLARED_FIELDS: &[&str] = &[
    "entries",
    "next_group_id",
    "retained_group_bytes",
    "accepting",
    "join_calls",
    "sync_calls",
    "heartbeat_calls",
    "coordinator_invalidations",
    "join_shutdown_recovery",
    "sync_shutdown_recovery",
    "heartbeat_shutdown_recovery",
    "coordinator_invalidation_shutdown_recovery",
    "join_recovery_fault",
    "sync_recovery_fault",
    "heartbeat_recovery_fault",
    "offset_commits",
];
pub(super) const ENTRY_DECLARED_FIELDS: &[&str] = &[
    "state",
    "catalog",
    "classic",
    "execution",
    "heartbeat",
    "rejoin",
    "rediscovery",
    "fault",
];
pub(super) const FORBIDDEN: &[&str] = &[
    "crate::driver",
    "crate::host",
    "crate::protocol",
    "kafka_driver",
    "kafka_wire",
    "kafka_wire_core",
    "kafka_wire_records",
    "tokio",
    "async_std",
    "smol",
    "std::future",
    "std::net",
    "std::thread",
    "std::time",
    "Condvar",
    "Instant::now",
    "Mutex",
    "RwLock",
    "Future",
    "async",
    "Callback",
    "Retry",
    "invalidate",
    "remove",
    "swap_remove",
    "retain",
    "pop",
    "clear",
    "drain",
];
pub(super) const REGISTRY_HOST_FORBIDDEN: &[&str] = &[
    "crate::admin",
    "crate::producer",
    "crate::protocol",
    "crate::transaction",
    "kafka_driver",
    "kafka_wire",
    "kafka_wire_core",
    "kafka_wire_records",
    "tokio",
    "async_std",
    "smol",
    "std::future",
    "std::net",
    "std::thread::spawn",
    "std::time::Instant",
    "std::time::SystemTime",
    "Condvar",
    "Instant::now",
    "Mutex",
    "RwLock",
    "Future",
    "Callback",
    "Metadata",
    "OperationDeadline",
    "Retry",
    "Route",
    "Runtime",
    "StartedEngineHost",
    "TrafficClass",
    "crate::Engine",
    "crate::exports",
    "async",
    "invalidate",
];
