//! Closed construction of concrete admin hosts from notifier publishers.

use crate::admin::{
    AdminCompletionPorts, AdminListOffsetsPublisher, AlterClientQuotasHost,
    AlterConsumerGroupOffsetsPublisher, AlterPartitionReassignmentsPublisher,
    AlterReplicaLogDirsHost, AlterUserScramCredentialsHost, CreateAclsHost, CreatePartitionsHost,
    CreateTopicsHost, DeleteAclsHost, DeleteConsumerGroupOffsetsHost, DeleteConsumerGroupsHost,
    DeleteRecordsHost, DeleteTopicsHost, DescribeAclsHost, DescribeClientQuotasHost,
    DescribeClusterHost, DescribeConfigsPublisher, DescribeConsumerGroupsHost, DescribeLogDirsHost,
    DescribeTopicsHost, DescribeUserScramCredentialsHost, ElectLeadersHost,
    IncrementalAlterConfigsHost, ListConsumerGroupOffsetsHost, ListConsumerGroupsHost,
    ListPartitionReassignmentsPublisher, RemoveConsumerGroupMembersHost,
};

pub(super) struct StartedAdminHosts {
    pub(super) create_topics: CreateTopicsHost,
    pub(super) create_acls: CreateAclsHost,
    pub(super) delete_acls: DeleteAclsHost,
    pub(super) delete_topics: DeleteTopicsHost,
    pub(super) delete_consumer_groups: DeleteConsumerGroupsHost,
    pub(super) delete_records: DeleteRecordsHost,
    pub(super) describe_acls: DescribeAclsHost,
    pub(super) describe_client_quotas: DescribeClientQuotasHost,
    pub(super) alter_client_quotas: AlterClientQuotasHost,
    pub(super) alter_user_scram_credentials: AlterUserScramCredentialsHost,
    pub(super) describe_user_scram_credentials: DescribeUserScramCredentialsHost,
    pub(super) describe_cluster: DescribeClusterHost,
    pub(super) describe_consumer_groups: DescribeConsumerGroupsHost,
    pub(super) describe_log_dirs: DescribeLogDirsHost,
    pub(super) alter_replica_log_dirs: AlterReplicaLogDirsHost,
    pub(super) create_partitions: CreatePartitionsHost,
    pub(super) describe_topics: DescribeTopicsHost,
    pub(super) describe_configs: DescribeConfigsPublisher,
    pub(super) incremental_alter_configs: IncrementalAlterConfigsHost,
    pub(super) list_consumer_group_offsets: ListConsumerGroupOffsetsHost,
    pub(super) list_consumer_groups: ListConsumerGroupsHost,
    pub(super) delete_consumer_group_offsets: DeleteConsumerGroupOffsetsHost,
    pub(super) alter_consumer_group_offsets: AlterConsumerGroupOffsetsPublisher,
    pub(super) admin_list_offsets: AdminListOffsetsPublisher,
    pub(super) list_partition_reassignments: ListPartitionReassignmentsPublisher,
    pub(super) alter_partition_reassignments: AlterPartitionReassignmentsPublisher,
    pub(super) elect_leaders: ElectLeadersHost,
    pub(super) remove_consumer_group_members: RemoveConsumerGroupMembersHost,
}

pub(super) fn start(ports: AdminCompletionPorts) -> StartedAdminHosts {
    let AdminCompletionPorts {
        create_topics,
        create_acls,
        delete_acls,
        delete_topics,
        delete_consumer_groups,
        delete_records,
        describe_acls,
        describe_client_quotas,
        alter_client_quotas,
        alter_user_scram_credentials,
        describe_user_scram_credentials,
        describe_cluster,
        describe_consumer_groups,
        describe_log_dirs,
        alter_replica_log_dirs,
        create_partitions,
        describe_topics,
        describe_configs,
        incremental_alter_configs,
        list_consumer_group_offsets,
        list_consumer_groups,
        delete_consumer_group_offsets,
        alter_consumer_group_offsets,
        admin_list_offsets,
        list_partition_reassignments,
        alter_partition_reassignments,
        elect_leaders,
        remove_consumer_group_members,
    } = ports;
    StartedAdminHosts {
        create_topics: CreateTopicsHost::new(create_topics),
        create_acls: CreateAclsHost::new(create_acls),
        delete_acls: DeleteAclsHost::new(delete_acls),
        delete_topics: DeleteTopicsHost::new(delete_topics),
        delete_consumer_groups: DeleteConsumerGroupsHost::new(delete_consumer_groups),
        delete_records: DeleteRecordsHost::new(delete_records),
        describe_acls: DescribeAclsHost::new(describe_acls),
        describe_client_quotas: DescribeClientQuotasHost::new(describe_client_quotas),
        alter_client_quotas: AlterClientQuotasHost::new(alter_client_quotas),
        alter_user_scram_credentials: AlterUserScramCredentialsHost::new(
            alter_user_scram_credentials,
        ),
        describe_user_scram_credentials: DescribeUserScramCredentialsHost::new(
            describe_user_scram_credentials,
        ),
        describe_cluster: DescribeClusterHost::new(describe_cluster),
        describe_consumer_groups: DescribeConsumerGroupsHost::new(describe_consumer_groups),
        describe_log_dirs: DescribeLogDirsHost::new(describe_log_dirs),
        alter_replica_log_dirs: AlterReplicaLogDirsHost::new(alter_replica_log_dirs),
        create_partitions: CreatePartitionsHost::new(create_partitions),
        describe_topics: DescribeTopicsHost::new(describe_topics),
        describe_configs,
        incremental_alter_configs: IncrementalAlterConfigsHost::new(incremental_alter_configs),
        list_consumer_group_offsets: ListConsumerGroupOffsetsHost::new(list_consumer_group_offsets),
        list_consumer_groups: ListConsumerGroupsHost::new(list_consumer_groups),
        delete_consumer_group_offsets: DeleteConsumerGroupOffsetsHost::new(
            delete_consumer_group_offsets,
        ),
        alter_consumer_group_offsets,
        admin_list_offsets,
        list_partition_reassignments,
        alter_partition_reassignments,
        elect_leaders: ElectLeadersHost::new(elect_leaders),
        remove_consumer_group_members: RemoveConsumerGroupMembersHost::new(
            remove_consumer_group_members,
        ),
    }
}
