//! Closed construction of concrete admin hosts from notifier publishers.

use crate::admin::{
    AbortPartitionTransactionHost, AddRaftVoterHost, AdminAlterShareGroupOffsetsPublisher,
    AdminCompletionPorts, AdminDeleteShareGroupOffsetsPublisher, AdminDescribeProducersHost,
    AdminDescribeShareGroupPublisher, AdminDescribeStreamsGroupPublisher,
    AdminDescribeTopicPartitionsHost, AdminDescribeTransactionsHost, AdminFenceProducersHost,
    AdminListOffsetsPublisher, AdminListShareGroupOffsetsPublisher, AdminListTransactionsHost,
    AlterClientQuotasHost, AlterConsumerGroupOffsetsPublisher,
    AlterPartitionReassignmentsPublisher, AlterReplicaLogDirsHost, AlterUserScramCredentialsHost,
    CreateAclsHost, CreateDelegationTokenHost, CreatePartitionsHost, CreateTopicsHost,
    DeleteAclsHost, DeleteConsumerGroupOffsetsHost, DeleteConsumerGroupsHost, DeleteRecordsHost,
    DeleteTopicsHost, DescribeAclsHost, DescribeClientQuotasHost, DescribeClusterHost,
    DescribeConfigsPublisher, DescribeConsumerGroupsHost, DescribeDelegationTokensHost,
    DescribeFeaturesHost, DescribeLogDirsHost, DescribeMetadataQuorumHost,
    DescribeReplicaLogDirsHost, DescribeTopicsHost, DescribeUserScramCredentialsHost,
    ElectLeadersHost, ExpireDelegationTokenHost, IncrementalAlterConfigsPublisher,
    LegacyAlterConfigsPublisher, ListConsumerGroupOffsetsHost, ListConsumerGroupsHost,
    ListPartitionReassignmentsPublisher, RemoveConsumerGroupMembersHost, RemoveRaftVoterHost,
    RenewDelegationTokenHost,
    list_client_metrics_resources::internal_api::ListClientMetricsResourcesHost,
    list_config_resources::ListConfigResourcesHost, unregister_broker::UnregisterBrokerHost,
    update_features::UpdateFeaturesHost,
};

pub(super) struct StartedAdminHosts {
    pub(super) abort_partition_transaction: AbortPartitionTransactionHost,
    pub(super) add_raft_voter: AddRaftVoterHost,
    pub(super) remove_raft_voter: RemoveRaftVoterHost,
    pub(super) create_topics: CreateTopicsHost,
    pub(super) create_acls: CreateAclsHost,
    pub(super) create_delegation_token: CreateDelegationTokenHost,
    pub(super) describe_delegation_tokens: DescribeDelegationTokensHost,
    pub(super) renew_delegation_token: RenewDelegationTokenHost,
    pub(super) expire_delegation_token: ExpireDelegationTokenHost,
    pub(super) delete_acls: DeleteAclsHost,
    pub(super) delete_topics: DeleteTopicsHost,
    pub(super) delete_consumer_groups: DeleteConsumerGroupsHost,
    pub(super) delete_records: DeleteRecordsHost,
    pub(super) describe_acls: DescribeAclsHost,
    pub(super) describe_client_quotas: DescribeClientQuotasHost,
    pub(super) alter_client_quotas: AlterClientQuotasHost,
    pub(super) alter_user_scram_credentials: AlterUserScramCredentialsHost,
    pub(super) update_features: UpdateFeaturesHost,
    pub(super) unregister_broker: UnregisterBrokerHost,
    pub(super) describe_user_scram_credentials: DescribeUserScramCredentialsHost,
    pub(super) describe_metadata_quorum: DescribeMetadataQuorumHost,
    pub(super) describe_producers: AdminDescribeProducersHost,
    pub(super) describe_topic_partitions: AdminDescribeTopicPartitionsHost,
    pub(super) describe_transactions: AdminDescribeTransactionsHost,
    pub(super) fence_producers: AdminFenceProducersHost,
    pub(super) list_transactions: AdminListTransactionsHost,
    pub(super) list_client_metrics_resources: ListClientMetricsResourcesHost,
    pub(super) list_config_resources: ListConfigResourcesHost,
    pub(super) describe_cluster: DescribeClusterHost,
    pub(super) describe_consumer_groups: DescribeConsumerGroupsHost,
    pub(super) describe_features: DescribeFeaturesHost,
    pub(super) describe_log_dirs: DescribeLogDirsHost,
    pub(super) describe_replica_log_dirs: DescribeReplicaLogDirsHost,
    pub(super) alter_replica_log_dirs: AlterReplicaLogDirsHost,
    pub(super) create_partitions: CreatePartitionsHost,
    pub(super) describe_topics: DescribeTopicsHost,
    pub(super) describe_configs: DescribeConfigsPublisher,
    pub(super) incremental_alter_configs: IncrementalAlterConfigsPublisher,
    pub(super) legacy_alter_configs: LegacyAlterConfigsPublisher,
    pub(super) list_consumer_group_offsets: ListConsumerGroupOffsetsHost,
    pub(super) list_consumer_groups: ListConsumerGroupsHost,
    pub(super) delete_consumer_group_offsets: DeleteConsumerGroupOffsetsHost,
    pub(super) delete_share_group_offsets: AdminDeleteShareGroupOffsetsPublisher,
    pub(super) list_share_group_offsets: AdminListShareGroupOffsetsPublisher,
    pub(super) alter_share_group_offsets: AdminAlterShareGroupOffsetsPublisher,
    pub(super) describe_share_group: AdminDescribeShareGroupPublisher,
    pub(super) describe_streams_group: AdminDescribeStreamsGroupPublisher,
    pub(super) alter_consumer_group_offsets: AlterConsumerGroupOffsetsPublisher,
    pub(super) admin_list_offsets: AdminListOffsetsPublisher,
    pub(super) list_partition_reassignments: ListPartitionReassignmentsPublisher,
    pub(super) alter_partition_reassignments: AlterPartitionReassignmentsPublisher,
    pub(super) elect_leaders: ElectLeadersHost,
    pub(super) remove_consumer_group_members: RemoveConsumerGroupMembersHost,
}

#[allow(
    clippy::too_many_lines,
    reason = "startup transfers every concrete admin completion port to exactly one host"
)]
pub(super) fn start(ports: AdminCompletionPorts) -> StartedAdminHosts {
    let AdminCompletionPorts {
        abort_partition_transaction,
        add_raft_voter,
        remove_raft_voter,
        create_topics,
        create_acls,
        create_delegation_token,
        describe_delegation_tokens,
        renew_delegation_token,
        expire_delegation_token,
        delete_acls,
        delete_topics,
        delete_consumer_groups,
        delete_records,
        describe_acls,
        describe_client_quotas,
        alter_client_quotas,
        alter_user_scram_credentials,
        update_features,
        unregister_broker,
        describe_user_scram_credentials,
        describe_metadata_quorum,
        describe_producers,
        describe_topic_partitions,
        describe_transactions,
        fence_producers,
        list_transactions,
        list_client_metrics_resources,
        list_config_resources,
        describe_cluster,
        describe_consumer_groups,
        describe_features,
        describe_log_dirs,
        describe_replica_log_dirs,
        alter_replica_log_dirs,
        create_partitions,
        describe_topics,
        describe_configs,
        incremental_alter_configs,
        legacy_alter_configs,
        list_consumer_group_offsets,
        list_consumer_groups,
        delete_consumer_group_offsets,
        delete_share_group_offsets,
        list_share_group_offsets,
        alter_share_group_offsets,
        describe_share_group,
        describe_streams_group,
        alter_consumer_group_offsets,
        admin_list_offsets,
        list_partition_reassignments,
        alter_partition_reassignments,
        elect_leaders,
        remove_consumer_group_members,
    } = ports;
    StartedAdminHosts {
        abort_partition_transaction: AbortPartitionTransactionHost::new(
            abort_partition_transaction,
        ),
        add_raft_voter: AddRaftVoterHost::new(add_raft_voter),
        remove_raft_voter: RemoveRaftVoterHost::new(remove_raft_voter),
        create_topics: CreateTopicsHost::new(create_topics),
        create_acls: CreateAclsHost::new(create_acls),
        create_delegation_token: CreateDelegationTokenHost::new(create_delegation_token),
        describe_delegation_tokens: DescribeDelegationTokensHost::new(describe_delegation_tokens),
        renew_delegation_token: RenewDelegationTokenHost::new(renew_delegation_token),
        expire_delegation_token: ExpireDelegationTokenHost::new(expire_delegation_token),
        delete_acls: DeleteAclsHost::new(delete_acls),
        delete_topics: DeleteTopicsHost::new(delete_topics),
        delete_consumer_groups: DeleteConsumerGroupsHost::new(delete_consumer_groups),
        delete_records: DeleteRecordsHost::new(delete_records),
        describe_acls: DescribeAclsHost::new(describe_acls),
        describe_client_quotas: DescribeClientQuotasHost::new(describe_client_quotas),
        alter_client_quotas: AlterClientQuotasHost::new(alter_client_quotas),
        alter_user_scram_credentials: AlterUserScramCredentialsHost::new(
            alter_user_scram_credentials,
        ),
        update_features: UpdateFeaturesHost::new(update_features),
        unregister_broker: UnregisterBrokerHost::new(unregister_broker),
        describe_user_scram_credentials: DescribeUserScramCredentialsHost::new(
            describe_user_scram_credentials,
        ),
        describe_metadata_quorum: DescribeMetadataQuorumHost::new(describe_metadata_quorum),
        describe_producers: AdminDescribeProducersHost::new(describe_producers),
        describe_topic_partitions: AdminDescribeTopicPartitionsHost::new(describe_topic_partitions),
        describe_transactions: AdminDescribeTransactionsHost::new(describe_transactions),
        fence_producers: AdminFenceProducersHost::new(fence_producers),
        list_transactions: AdminListTransactionsHost::new(list_transactions),
        list_client_metrics_resources: ListClientMetricsResourcesHost::new(
            list_client_metrics_resources,
        ),
        list_config_resources: ListConfigResourcesHost::new(list_config_resources),
        describe_cluster: DescribeClusterHost::new(describe_cluster),
        describe_consumer_groups: DescribeConsumerGroupsHost::new(describe_consumer_groups),
        describe_features: DescribeFeaturesHost::new(describe_features),
        describe_log_dirs: DescribeLogDirsHost::new(describe_log_dirs),
        describe_replica_log_dirs: DescribeReplicaLogDirsHost::new(describe_replica_log_dirs),
        alter_replica_log_dirs: AlterReplicaLogDirsHost::new(alter_replica_log_dirs),
        create_partitions: CreatePartitionsHost::new(create_partitions),
        describe_topics: DescribeTopicsHost::new(describe_topics),
        describe_configs,
        incremental_alter_configs,
        legacy_alter_configs,
        list_consumer_group_offsets: ListConsumerGroupOffsetsHost::new(list_consumer_group_offsets),
        list_consumer_groups: ListConsumerGroupsHost::new(list_consumer_groups),
        delete_consumer_group_offsets: DeleteConsumerGroupOffsetsHost::new(
            delete_consumer_group_offsets,
        ),
        delete_share_group_offsets,
        list_share_group_offsets,
        alter_share_group_offsets,
        describe_share_group,
        describe_streams_group,
        alter_consumer_group_offsets,
        admin_list_offsets,
        list_partition_reassignments,
        alter_partition_reassignments,
        elect_leaders: ElectLeadersHost::new(elect_leaders),
        remove_consumer_group_members: RemoveConsumerGroupMembersHost::new(
            remove_consumer_group_members,
        ),
    }
}
