//! Exact forbidden capability sets for private group-consumer host seams.

pub(super) const ROOT: &str = "crates/kafka-client-engine/src/engine_host/";
pub(super) const SCHEDULING: &[&str] = &[
    "crate::admin",
    "crate::producer",
    "crate::protocol",
    "crate::transaction",
    "kafka_driver",
    "kafka_wire",
    "kafka_wire_core",
    "kafka_wire_records",
    "tokio",
    "async_std",
    "smol",
    "std::thread::spawn",
    "std::time::Instant",
    "std::time::SystemTime",
    "Instant::now",
    "Callback",
    "Metadata",
    "OperationDeadline",
    "Retry",
    "Route",
    "Runtime",
    "StartedEngineHost",
    "TrafficClass",
    "crate::Engine",
    "crate::exports",
    "async",
    "invalidate",
];
pub(super) const SHUTDOWN: &[&str] = &[
    "crate::admin",
    "crate::driver",
    "crate::producer",
    "crate::protocol",
    "crate::transaction",
    "kafka_client_core",
    "kafka_driver",
    "kafka_wire",
    "kafka_wire_core",
    "kafka_wire_records",
    "tokio",
    "async_std",
    "smol",
    "std::thread",
    "std::time",
    "Callback",
    "Metadata",
    "OperationDeadline",
    "Retry",
    "Route",
    "Runtime",
    "StartedEngineHost",
    "TrafficClass",
    "crate::Engine",
    "crate::exports",
    "async",
    "invalidate",
];
pub(super) const RULES: &[(&str, &[&str])] = &[
    ("group_consumer.rs", SCHEDULING),
    ("group_consumer_shutdown.rs", SHUTDOWN),
];
